### ISSUE TITLE
Missing... test

### ISSUE THREAD

**Issue by Jo0001** [Jo0001/GitHubTest#28]
/viaversion dump Output

https://dump.viaversion.com/991d0f8cd6b646829a40860f2b4a722fe7208aa1e00ebda9a029fc6258c498b5
Console Error

Put the paste.gg link or text here.

Bug Description

A server that I connect to has updated to 1.19.3 and I'm running Forge Client side mods on 1.19.2.

When I connect with 1.19.2 and try to chat, I receive "Chat disabled due to missing profile public key. Please try reconnecting"

When I connect with 1.19.3 chat works as expected.
Steps to Reproduce

    Log in via a 1.19.2 client.
    Try to chat - doesn't work
    Log in via a 1.19.3 client.
    Try to chat - should work

Expected Behavior

When trying to chat on the 1.19.2 client, you should receive a message saying, "Chat disabled due to missing profile public key. Please try reconnecting."
Additional Server Info

No response
Checklist

Via plugins are only running on EITHER the backend servers (e.g. Paper) OR the proxy (e.g. BungeeCord), not on both.
I have included a ViaVersion dump.
If applicable, I have included a paste (not a screenshot) of the error.
I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 3624--Spigot--d90018e--ab1586c%20%28MC%3A%201.19.3%29](https://img.shields.io/badge/Platform-3624--Spigot--d90018e--ab1586c%20%28MC%3A%201.19.3%29-3498db?style=flat-square) </br>![ViaVersion (4.5.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.5.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.5.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.5.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(2.0.2): 17 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-17%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><br>To fix `missing profile public key` checkout <a href='https://gist.github.com/Jo0001/4d14eb4d3ae51b11eb90ba3296c8095b'>this guide</a><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump

**Comment by Jo0001** [comment]
When I connect with 1.19.2 and try to chat, I receive "Chat disabled due to missing profile public key. Please try reconnecting"

**Comment by Barvalg** [comment]
![Platform: 3624--Spigot--d90018e--ab1586c%20%28MC%3A%201.19.3%29](https://img.shields.io/badge/Platform-3624--Spigot--d90018e--ab1586c%20%28MC%3A%201.19.3%29-3498db?style=flat-square) </br>![ViaVersion (4.5.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.5.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.5.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.5.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(2.0.2): 17 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-17%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>To fix the `missing profile public key` issue  checkout <a target='_blank' href='https://gist.github.com/Jo0001/4d14eb4d3ae51b11eb90ba3296c8095b'>this guide</a><br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump

**Comment by Jo0001** [comment]
https://dump.viaversion.com/3037500a343e4710eaedfda584a3c02fafadc8a614d4c56a9f0530d355128061

**Comment by Barvalg** [comment]
![Platform: git%3ABungeeCord--Bootstrap%3A1.19--R0.1--SNAPSHOT%3A19424ab%3A1678](https://img.shields.io/badge/Platform-git%3ABungeeCord--Bootstrap%3A1.19--R0.1--SNAPSHOT%3A19424ab%3A1678-3498db?style=flat-square) </br>![Proxy is 12 builds behind](https://img.shields.io/badge/Your%20proxy%20is%2012%20build(s)%20behind.%20Please%20update%20to%20the%20latest%20version-orange?style=flat-square) </br>![ViaVersion (4.6.2): 1 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.6.2)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.3): 1 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.3)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.6.1): 9 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.6.1)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by Jo0001** [comment]
https://dump.viaversion.com/c368a03750625c99060e3a33e23fa69160c40b065aa612a3e2011ee5ff58f100

**Comment by Barvalg** [comment]
![Platform: velocity%203.2.0--SNAPSHOT%20%28git--c7ba5255--b244%29](https://img.shields.io/badge/Platform-velocity%203.2.0--SNAPSHOT%20%28git--c7ba5255--b244%29-3498db?style=flat-square) </br>![Proxy is 3 builds behind](https://img.shields.io/badge/Your%20proxy%20is%203%20build(s)%20behind.%20Please%20update%20to%20the%20latest%20version-orange?style=flat-square) </br>![ViaVersion (4.6.2): 3 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.6.2)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.6.1): 9 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.6.1)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by Jo0001** [comment]
https://dump.viaversion.com/991d0f8cd6b646829a40860f2b4a722fe7208aa1e00ebda9a029fc6258c498b5

**Comment by Barvalg** [comment]
![Platform: 3624--Spigot--d90018e--ab1586c%20%28MC%3A%201.19.3%29](https://img.shields.io/badge/Platform-3624--Spigot--d90018e--ab1586c%20%28MC%3A%201.19.3%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(4.5.1)-Outdated!-red?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.5.1)-Outdated!-red?style=flat-square) </br>![ViaRewind: Outdated](https://img.shields.io/badge/ViaRewind%20(2.0.2)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by Jo0001** [comment]
https://dump.viaversion.com/7ec636d10220100ec84f9352aec1310afae91da77374d1783cc15e528622b10d

**Comment by Barvalg** [comment]
![Platform: git--Paper--519%20%28MC%3A%201.19.4%29](https://img.shields.io/badge/Platform-git--Paper--519%20%28MC%3A%201.19.4%29-3498db?style=flat-square) </br>![ViaVersion (4.6.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.6.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.6.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.6.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Jo0001** [comment]
[Netty Server IO https://github.com/ViaVersion/ViaVersion/issues/2/ERROR]: Invalid signature for profile public key.
Try restarting your game.
net.minecraft.server.network.LoginListener$a: Missing profile public key.
This server requires secure profiles.
at net.minecraft.server.network.LoginListener.a(LoginListener.java:214) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
at net.minecraft.server.network.LoginListener.a(LoginListener.java:240) [spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
at net.minecraft.network.protocol.login.PacketLoginInStart.a(SourceFile:23) [spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
at net.minecraft.network.protocol.login.PacketLoginInStart.a(SourceFile:10) [spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
at net.minecraft.network.NetworkManager.a(NetworkManager.java:180) [spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
at net.minecraft.network.NetworkManager.a(NetworkManager.java:164) [spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:1) [spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.77.Final.jar:4.1.77.Final]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) [netty-codec-4.1.77.Final.jar:4.1.77.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-codec-4.1.77.Final.jar:4.1.77.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelR

**Comment by Jo0001** [comment]
https://dump.viaversion.com/7ec636d10220100ec84f9352aec1310afae91da77374d1783cc15e528622b10d

[Netty Server IO https://github.com/ViaVersion/ViaVersion/issues/2/ERROR]: Invalid signature for profile public key.
Try restarting your game.
net.minecraft.server.network.LoginListener$a: Missing profile public key.
This server requires secure profiles.
at net.minecraft.server.network.LoginListener.a(LoginListener.java:214) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
at net.minecraft.server.network.LoginListener.a(LoginListener.java:240) [spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
at net.minecraft.network.protocol.login.PacketLoginInStart.a(SourceFile:23) [spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
at net.minecraft.network.protocol.login.PacketLoginInStart.a(SourceFile:10) [spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
at net.minecraft.network.NetworkManager.a(NetworkManager.java:180) [spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
at net.minecraft.network.NetworkManager.a(NetworkManager.java:164) [spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:1) [spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.77.Final.jar:4.1.77.Final]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) [netty-codec-4.1.77.Final.jar:4.1.77.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-codec-4.1.77.Final.jar:4.1.77.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelR

**Comment by Barvalg** [comment]
![Platform: git--Paper--519%20%28MC%3A%201.19.4%29](https://img.shields.io/badge/Platform-git--Paper--519%20%28MC%3A%201.19.4%29-3498db?style=flat-square) </br>![ViaVersion (4.6.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.6.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.6.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.6.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br><br>To fix the `missing profile public key` issue  checkout <a target='_blank' href='https://gist.github.com/Jo0001/4d14eb4d3ae51b11eb90ba3296c8095b'>this guide</a><br>

**Comment by Jo0001** [comment]
https://dump.viaversion.com/c3fb7661dc4a09094666438909d1577e6468827d2aee35872d830f8a75a038ee

**Comment by Jo0001** [comment]
https://dump.viaversion.com/a148d6df161a651391159cd1769ea942e911a015acf26b59de3a211927c7d7e8

**Comment by Jo0001** [comment]
https://dump.viaversion.com/e10acc14e6a64b00af9d1b7b12938da9d5dd5f56dd78db8fb599beb57c8813b3

**Comment by Barvalg** [comment]
![Platform: git%3AWaterfall--Bootstrap%3A1.19--R0.1--SNAPSHOT%3Ae0a029e%3A520](https://img.shields.io/badge/Platform-git%3AWaterfall--Bootstrap%3A1.19--R0.1--SNAPSHOT%3Ae0a029e%3A520-3498db?style=flat-square) </br>![Proxy is 6 builds behind](https://img.shields.io/badge/Your%20proxy%20is%206%20build(s)%20behind.%20Please%20update%20to%20the%20latest%20version-orange?style=flat-square) </br>![ViaVersion (4.6.2): 6 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.6.2)-6%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.6.0)-Outdated!-red?style=flat-square) </br>![ViaRewind: Outdated](https://img.shields.io/badge/ViaRewind%20(2.0.2)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>
